### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by dontyna** [ondata/5x1000#2]
Cambiare 

> La nostra associazione si batte per la trasparenza della pubblica amministrazione e l'accessibilità dei dati pubblici: con il tuo aiuto saremo più forti. Che aspetti? :-)

in 

> La nostra associazione si batte per la trasparenza della pubblica amministrazione e l'accessibilità dei dati pubblici: dona il tuo 5x1000 per un'Italia più trasparente e moderna per tutti.

**Comment by nelsonmau** [comment]
fatto, ma ho tolto "moderna" e scritto "aperta"
