### ISSUE TITLE
Sostieni in navbar del sito principale? diventando ondata.it/sostieni?

### ISSUE THREAD

**Issue by giuragu** [ondata/5x1000#4]
Vedendo il sito mi veniva in mente che così si può perdere il legame con il sito associativo. Non è il caso che Sostieni e le sue voci di menu, pensate specificamente in questo caso per il 5x1000, diventino una one page dentro un ipotetico ondata.it/sostieni?

**Comment by nelsonmau** [comment]
sì hai ragione sulla prima parte (mentre non sono d'accordo sul creare ondata.it/sostieni perché ci incasina). Metto il pulsante in hp di ondata in questi giorni

**Comment by nelsonmau** [comment]
cmq alla fine avevo fatto, chiudo qui
